/**
 * A function to validate the token generated by crypto.randomUUID()
 * @param token - The token to validate
 * @returns - A boolean value
 */
export function validateToken(token: string) {
  const validationRegex = /^[a-z,0-9,-]{36,36}$/
  return validationRegex.test(token)
}
